version: "3.7"
services:
  redis:
    image: redis:alpine
    ports:
      - "10370:6379"

  mysql:
    image: percona:5.7
    ports:
      - "10371:3306"
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: app
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  web:
    build:
      context: .
      dockerfile: Dockerfile.openresty
      args:
        - REQUIREMENTS=local
    links:
      - mysql:db1
      - redis:cache1
      - app:localhost
    ports:
      - "10372:80"
    # If want to test the image that runs on LIVE env, please mark this section
    volumes:
      - .:/var/www/project/
    command: "sh -c 'sed -i \"s/172.16.0.10/127.0.0.11/g\" /usr/local/openresty/nginx/conf/nginx.conf && echo \"\" > /etc/hosts && openresty -p .'"
    # This is exactly what is run on gcloud:
    # command: openresty -p .
    environment:
      - DEPLOY=dev
      - EVENT_REGION=tw

  app:
    build:
      context: .
      dockerfile: Dockerfile.gunicorn
      args:
        - REQUIREMENTS=local
    links:
      - redis:cache1
      - mysql:db1
    expose:
      - "8000"
    # If want to test the image that runs on LIVE env, please mark this section
    volumes:
      - .:/var/www/project/
    command: "sh -c ''"
    working_dir: /var/www/project/
    environment:
      - DEPLOY=dev
